name: Update Portfolio

on:
  
  workflow_dispatch:
  
  push:
    branches: [ master ]

jobs:
  run_update:
    runs-on: ubuntu-latest

    steps:
      - run: pwd
      - run: ls -a
        
      - name: Checkout Portfolio
        uses: actions/checkout@v2

      - run: pwd
      - run: ls -a
        
      - name: Checkout ajayaujla.github.io
        uses: actions/checkout@v2
        with:
          repository: AjayAujla/ajayaujla.github.io
          token: ${{ secrets.API_TOKEN }}
      
      - run: pwd
      - run: ls -a

#       - name: Git Configuration
#         run: |
#           git config --global user.email "ajay.aujla@hotmail.com"
#           git config --global user.name "AjayAujla"

      - name: Squash
        run: |
          cd Portfolio
          git reset $(git commit-tree HEAD^{tree} -m "Initial commit")
          cd ..

      - name: Move Squashed
        run: |
          cd ajayaujla.github.io
          rm -f "ajayaujla.github.io/{*,.*}" 
          cd ..
          mv Portfolio/!(git) ajayaujla.github.io/

      - name: Update Remote
        run: |
          git push -f
